# Generated by Django 3.2.5 on 2021-08-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_bio',
            field=models.CharField(max_length=500),
        ),
    ]
